### PR TITLE
fix: Fix error caused when input data is mixed with datetime and string types

### PR DESCRIPTION
**Pull request by tashiro-akira**
@AkiraUra @kimusaku 
Fix error caused when input data contains a mix of datetime and string types that rarely convert to datetime types.
Please check.

### CODE REVIEW

**Comment by AkiraUra** [comment]
@tashiro-akira Could you make this PR pass the lint check? Thanks.

**Comment by tashiro-akira** [comment]
You can check the error by creating and running the following main.py

```
import numpy as np
import pandas as pd
from sapientml import SapientML

from pandas.api.types import infer_dtype
from pandas.core.dtypes.common import is_bool_dtype
import datetime


df = pd.DataFrame({'a': [1,2]*10, 'b': ["moji"]*19+[datetime.datetime.now()], 'y': [1,0]*10})

cls_ = SapientML(
    target_columns=['y'],
    task_type='classification',
)
cls_.fit(
    training_data=df,
)
```

**Review by AkiraUra — COMMENTED** [review]
Thank you for your PR.

I think only the following two changes are sufficient. What do you think?

## 1(generator.py)
```python
            df[only_str] = np.where(pd.to_numeric(df[col], errors="coerce").isnull(), df[col], np.nan)
```
->
```python
            df[only_str] = np.where(pd.to_numeric(df[col], errors="coerce").isnull(), df[col], np.nan)
            # Use np.where to prevent transforming NaN to 'nan'
            df[only_str] = np.where(df[only_str].notnull(), df[only_str].astype(str), np.nan)

```

## 2 (handle_mixed_typed_columns.py.jinja)

```
{% if training %}
    train_dataset[col + '__str'] = np.where(pd.to_numeric(train_dataset[col], errors='coerce').isnull(), train_dataset[col], np.nan)
    train_dataset[col + '__str'] = np.where(train_dataset[col + '__str'].notnull(), train_dataset[col + '__str'].astype(str), np.nan)  # ADDED
    train_dataset[col + '__num'] = np.where(pd.to_numeric(train_dataset[col], errors='coerce').isnull(), np.nan, train_dataset[col]).astype(float)
    train_dataset = train_dataset.drop(col, axis=1)
{% endif %}
{% if test %}
    test_dataset[col + '__str'] = np.where(pd.to_numeric(test_dataset[col], errors='coerce').isnull(), test_dataset[col], np.nan)
    test_dataset[col + '__str'] = np.where(test_dataset[col + '__str'].notnull(), test_dataset[col + '__str'].astype(str), np.nan) # ADDED
    test_dataset[col + '__num'] = np.where(pd.to_numeric(test_dataset[col], errors='coerce').isnull(), np.nan, test_dataset[col]).astype(float)
    test_dataset = test_dataset.drop(col, axis=1)
{% endif %}
```

**Comment by tashiro-akira** [comment]
All the points of the review have been reflected.

**Review by AkiraUra — APPROVED** [review]
Thank you.

**Pull request merged**
